// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: api/proto/portcullis/v1/portcullis.proto

package portcullisv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RateLimiterService_CheckRateLimit_FullMethodName = "/portcullis.v1.RateLimiterService/CheckRateLimit"
	RateLimiterService_GetLimitStatus_FullMethodName = "/portcullis.v1.RateLimiterService/GetLimitStatus"
	RateLimiterService_ResetLimit_FullMethodName     = "/portcullis.v1.RateLimiterService/ResetLimit"
	RateLimiterService_Report_FullMethodName         = "/portcullis.v1.RateLimiterService/Report"
)

// RateLimiterServiceClient is the client API for RateLimiterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RateLimiterServiceClient interface {
	// CheckRateLimit checks if a request should be allowed based on rate limiting rules
	CheckRateLimit(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	// GetLimitStatus returns the current rate limit status for an identifier
	GetLimitStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// ResetLimit resets the rate limit for an identifier
	ResetLimit(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error)
	// Report records a request the caller already served, so the detection plane
	// can see traffic that never passed through the gateway. Public.
	Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
}

type rateLimiterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRateLimiterServiceClient(cc grpc.ClientConnInterface) RateLimiterServiceClient {
	return &rateLimiterServiceClient{cc}
}

func (c *rateLimiterServiceClient) CheckRateLimit(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, RateLimiterService_CheckRateLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rateLimiterServiceClient) GetLimitStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, RateLimiterService_GetLimitStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rateLimiterServiceClient) ResetLimit(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*ResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetResponse)
	err := c.cc.Invoke(ctx, RateLimiterService_ResetLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rateLimiterServiceClient) Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, RateLimiterService_Report_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RateLimiterServiceServer is the server API for RateLimiterService service.
// All implementations must embed UnimplementedRateLimiterServiceServer
// for forward compatibility.
type RateLimiterServiceServer interface {
	// CheckRateLimit checks if a request should be allowed based on rate limiting rules
	CheckRateLimit(context.Context, *CheckRequest) (*CheckResponse, error)
	// GetLimitStatus returns the current rate limit status for an identifier
	GetLimitStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	// ResetLimit resets the rate limit for an identifier
	ResetLimit(context.Context, *ResetRequest) (*ResetResponse, error)
	// Report records a request the caller already served, so the detection plane
	// can see traffic that never passed through the gateway. Public.
	Report(context.Context, *ReportRequest) (*ReportResponse, error)
	mustEmbedUnimplementedRateLimiterServiceServer()
}

// UnimplementedRateLimiterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRateLimiterServiceServer struct{}

func (UnimplementedRateLimiterServiceServer) CheckRateLimit(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckRateLimit not implemented")
}
func (UnimplementedRateLimiterServiceServer) GetLimitStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLimitStatus not implemented")
}
func (UnimplementedRateLimiterServiceServer) ResetLimit(context.Context, *ResetRequest) (*ResetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetLimit not implemented")
}
func (UnimplementedRateLimiterServiceServer) Report(context.Context, *ReportRequest) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedRateLimiterServiceServer) mustEmbedUnimplementedRateLimiterServiceServer() {}
func (UnimplementedRateLimiterServiceServer) testEmbeddedByValue()                            {}

// UnsafeRateLimiterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RateLimiterServiceServer will
// result in compilation errors.
type UnsafeRateLimiterServiceServer interface {
	mustEmbedUnimplementedRateLimiterServiceServer()
}

func RegisterRateLimiterServiceServer(s grpc.ServiceRegistrar, srv RateLimiterServiceServer) {
	// If the following call panics, it indicates UnimplementedRateLimiterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RateLimiterService_ServiceDesc, srv)
}

func _RateLimiterService_CheckRateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimiterServiceServer).CheckRateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimiterService_CheckRateLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimiterServiceServer).CheckRateLimit(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RateLimiterService_GetLimitStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimiterServiceServer).GetLimitStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimiterService_GetLimitStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimiterServiceServer).GetLimitStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RateLimiterService_ResetLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimiterServiceServer).ResetLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimiterService_ResetLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimiterServiceServer).ResetLimit(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RateLimiterService_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimiterServiceServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimiterService_Report_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimiterServiceServer).Report(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RateLimiterService_ServiceDesc is the grpc.ServiceDesc for RateLimiterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RateLimiterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "portcullis.v1.RateLimiterService",
	HandlerType: (*RateLimiterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckRateLimit",
			Handler:    _RateLimiterService_CheckRateLimit_Handler,
		},
		{
			MethodName: "GetLimitStatus",
			Handler:    _RateLimiterService_GetLimitStatus_Handler,
		},
		{
			MethodName: "ResetLimit",
			Handler:    _RateLimiterService_ResetLimit_Handler,
		},
		{
			MethodName: "Report",
			Handler:    _RateLimiterService_Report_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/portcullis/v1/portcullis.proto",
}

const (
	AdminService_SetTier_FullMethodName       = "/portcullis.v1.AdminService/SetTier"
	AdminService_ClearTier_FullMethodName     = "/portcullis.v1.AdminService/ClearTier"
	AdminService_ListTiers_FullMethodName     = "/portcullis.v1.AdminService/ListTiers"
	AdminService_ListDecisions_FullMethodName = "/portcullis.v1.AdminService/ListDecisions"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminService is the operator surface. Every RPC requires an admin bearer
// token.
type AdminServiceClient interface {
	// SetTier writes a manual tier entry for an identity.
	SetTier(ctx context.Context, in *SetTierRequest, opts ...grpc.CallOption) (*SetTierResponse, error)
	// ClearTier removes an identity's tier entry. Idempotent.
	ClearTier(ctx context.Context, in *ClearTierRequest, opts ...grpc.CallOption) (*ClearTierResponse, error)
	// ListTiers returns every active tier entry.
	ListTiers(ctx context.Context, in *ListTiersRequest, opts ...grpc.CallOption) (*ListTiersResponse, error)
	// ListDecisions returns audit records, newest first.
	ListDecisions(ctx context.Context, in *ListDecisionsRequest, opts ...grpc.CallOption) (*ListDecisionsResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) SetTier(ctx context.Context, in *SetTierRequest, opts ...grpc.CallOption) (*SetTierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTierResponse)
	err := c.cc.Invoke(ctx, AdminService_SetTier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ClearTier(ctx context.Context, in *ClearTierRequest, opts ...grpc.CallOption) (*ClearTierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearTierResponse)
	err := c.cc.Invoke(ctx, AdminService_ClearTier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListTiers(ctx context.Context, in *ListTiersRequest, opts ...grpc.CallOption) (*ListTiersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTiersResponse)
	err := c.cc.Invoke(ctx, AdminService_ListTiers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListDecisions(ctx context.Context, in *ListDecisionsRequest, opts ...grpc.CallOption) (*ListDecisionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDecisionsResponse)
	err := c.cc.Invoke(ctx, AdminService_ListDecisions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// AdminService is the operator surface. Every RPC requires an admin bearer
// token.
type AdminServiceServer interface {
	// SetTier writes a manual tier entry for an identity.
	SetTier(context.Context, *SetTierRequest) (*SetTierResponse, error)
	// ClearTier removes an identity's tier entry. Idempotent.
	ClearTier(context.Context, *ClearTierRequest) (*ClearTierResponse, error)
	// ListTiers returns every active tier entry.
	ListTiers(context.Context, *ListTiersRequest) (*ListTiersResponse, error)
	// ListDecisions returns audit records, newest first.
	ListDecisions(context.Context, *ListDecisionsRequest) (*ListDecisionsResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) SetTier(context.Context, *SetTierRequest) (*SetTierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTier not implemented")
}
func (UnimplementedAdminServiceServer) ClearTier(context.Context, *ClearTierRequest) (*ClearTierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearTier not implemented")
}
func (UnimplementedAdminServiceServer) ListTiers(context.Context, *ListTiersRequest) (*ListTiersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTiers not implemented")
}
func (UnimplementedAdminServiceServer) ListDecisions(context.Context, *ListDecisionsRequest) (*ListDecisionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDecisions not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_SetTier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SetTier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SetTier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SetTier(ctx, req.(*SetTierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ClearTier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearTierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ClearTier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ClearTier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ClearTier(ctx, req.(*ClearTierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListTiers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTiersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListTiers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListTiers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListTiers(ctx, req.(*ListTiersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListDecisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDecisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListDecisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListDecisions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListDecisions(ctx, req.(*ListDecisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "portcullis.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetTier",
			Handler:    _AdminService_SetTier_Handler,
		},
		{
			MethodName: "ClearTier",
			Handler:    _AdminService_ClearTier_Handler,
		},
		{
			MethodName: "ListTiers",
			Handler:    _AdminService_ListTiers_Handler,
		},
		{
			MethodName: "ListDecisions",
			Handler:    _AdminService_ListDecisions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/portcullis/v1/portcullis.proto",
}
