// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: api/proto/portcullis/v1/portcullis.proto

package portcullisv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Attributes describes the request a check is being made for. It is optional
// and only feeds the signals pipeline; it never affects the decision.
type Attributes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw request path.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// HTTP method.
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// Raw User-Agent header, classified by code, never by a model.
	UserAgent     string `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attributes) Reset() {
	*x = Attributes{}
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attributes) ProtoMessage() {}

func (x *Attributes) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attributes.ProtoReflect.Descriptor instead.
func (*Attributes) Descriptor() ([]byte, []int) {
	return file_api_proto_portcullis_v1_portcullis_proto_rawDescGZIP(), []int{0}
}

func (x *Attributes) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Attributes) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Attributes) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type CheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the rate limit (e.g., IP address, API key, user ID)
	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Resource being accessed (e.g., endpoint path, API method)
	Resource string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// Number of tokens to consume (default: 1)
	Tokens int64 `protobuf:"varint,3,opt,name=tokens,proto3" json:"tokens,omitempty"`
	// Optional request attributes for the signals pipeline.
	Attributes    *Attributes `protobuf:"bytes,4,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_portcullis_v1_portcullis_proto_rawDescGZIP(), []int{1}
}

func (x *CheckRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *CheckRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CheckRequest) GetTokens() int64 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *CheckRequest) GetAttributes() *Attributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type CheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the request is allowed
	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// Maximum number of requests allowed in the window
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Number of requests remaining in the current window
	Remaining int64 `protobuf:"varint,3,opt,name=remaining,proto3" json:"remaining,omitempty"`
	// Seconds until the rate limit resets (only set if not allowed)
	RetryAfterSeconds int64 `protobuf:"varint,4,opt,name=retry_after_seconds,json=retryAfterSeconds,proto3" json:"retry_after_seconds,omitempty"`
	// Unix timestamp when the rate limit will reset
	ResetAtUnix   int64 `protobuf:"varint,5,opt,name=reset_at_unix,json=resetAtUnix,proto3" json:"reset_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_portcullis_v1_portcullis_proto_rawDescGZIP(), []int{2}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CheckResponse) GetRemaining() int64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *CheckResponse) GetRetryAfterSeconds() int64 {
	if x != nil {
		return x.RetryAfterSeconds
	}
	return 0
}

func (x *CheckResponse) GetResetAtUnix() int64 {
	if x != nil {
		return x.ResetAtUnix
	}
	return 0
}

type StatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the rate limit
	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Resource being accessed (optional, for resource-specific limits)
	Resource      string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_portcullis_v1_portcullis_proto_rawDescGZIP(), []int{3}
}

func (x *StatusRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *StatusRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of requests allowed in the window
	Limit int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Number of requests remaining in the current window
	Remaining int64 `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	// Unix timestamp when the rate limit will reset
	ResetAtUnix int64 `protobuf:"varint,3,opt,name=reset_at_unix,json=resetAtUnix,proto3" json:"reset_at_unix,omitempty"`
	// Current number of tokens available
	TokensAvailable float64 `protobuf:"fixed64,4,opt,name=tokens_available,json=tokensAvailable,proto3" json:"tokens_available,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_portcullis_v1_portcullis_proto_rawDescGZIP(), []int{4}
}

func (x *StatusResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *StatusResponse) GetRemaining() int64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *StatusResponse) GetResetAtUnix() int64 {
	if x != nil {
		return x.ResetAtUnix
	}
	return 0
}

func (x *StatusResponse) GetTokensAvailable() float64 {
	if x != nil {
		return x.TokensAvailable
	}
	return 0
}

type ResetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the rate limit to reset
	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Resource to reset (optional, for resource-specific limits)
	Resource      string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_portcullis_v1_portcullis_proto_rawDescGZIP(), []int{5}
}

func (x *ResetRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *ResetRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type ResetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the reset was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Message describing the result
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_portcullis_v1_portcullis_proto_rawDescGZIP(), []int{6}
}

func (x *ResetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rate-limit identity of the client that made the request.
	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Route template or configured resource.
	Resource string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// Status code the caller served, or 0 when unknown.
	Status int32 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	// Raw request path.
	Path string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	// HTTP method.
	Method string `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	// Raw User-Agent header.
	UserAgent     string `protobuf:"bytes,6,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_portcullis_v1_portcullis_proto_rawDescGZIP(), []int{7}
}

func (x *ReportRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *ReportRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ReportRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ReportRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReportRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ReportRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type ReportResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the observation was accepted. Recording is lossy by design, so
	// acceptance means "handed to the pipeline", not "retained".
	Accepted      bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_portcullis_v1_portcullis_proto_rawDescGZIP(), []int{8}
}

func (x *ReportResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type SetTierRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity the tier applies to.
	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// Tier name: normal | watch | throttle | strict | block.
	Tier string `protobuf:"bytes,2,opt,name=tier,proto3" json:"tier,omitempty"`
	// How long the entry lasts. Zero uses the configured tier TTL.
	TtlSeconds int64 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	// Operator-supplied note. Logged, never sent to an external service.
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTierRequest) Reset() {
	*x = SetTierRequest{}
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTierRequest) ProtoMessage() {}

func (x *SetTierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTierRequest.ProtoReflect.Descriptor instead.
func (*SetTierRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_portcullis_v1_portcullis_proto_rawDescGZIP(), []int{9}
}

func (x *SetTierRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *SetTierRequest) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *SetTierRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *SetTierRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SetTierResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity the stored entry applies to.
	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// Stored tier name.
	Tier string `protobuf:"bytes,2,opt,name=tier,proto3" json:"tier,omitempty"`
	// Unix timestamp when the entry expires, or 0 when it never does.
	UntilUnix int64 `protobuf:"varint,3,opt,name=until_unix,json=untilUnix,proto3" json:"until_unix,omitempty"`
	// Where the entry came from: "manual" for operator writes.
	Source string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	// Audit record that produced the entry, when there was one.
	DecisionId    string `protobuf:"bytes,5,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTierResponse) Reset() {
	*x = SetTierResponse{}
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTierResponse) ProtoMessage() {}

func (x *SetTierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTierResponse.ProtoReflect.Descriptor instead.
func (*SetTierResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_portcullis_v1_portcullis_proto_rawDescGZIP(), []int{10}
}

func (x *SetTierResponse) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *SetTierResponse) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *SetTierResponse) GetUntilUnix() int64 {
	if x != nil {
		return x.UntilUnix
	}
	return 0
}

func (x *SetTierResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SetTierResponse) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

type ClearTierRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity to clear.
	Identity      string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearTierRequest) Reset() {
	*x = ClearTierRequest{}
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearTierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearTierRequest) ProtoMessage() {}

func (x *ClearTierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearTierRequest.ProtoReflect.Descriptor instead.
func (*ClearTierRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_portcullis_v1_portcullis_proto_rawDescGZIP(), []int{11}
}

func (x *ClearTierRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type ClearTierResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Always true: clearing an absent entry is a success.
	Cleared       bool `protobuf:"varint,1,opt,name=cleared,proto3" json:"cleared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearTierResponse) Reset() {
	*x = ClearTierResponse{}
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearTierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearTierResponse) ProtoMessage() {}

func (x *ClearTierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearTierResponse.ProtoReflect.Descriptor instead.
func (*ClearTierResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_portcullis_v1_portcullis_proto_rawDescGZIP(), []int{12}
}

func (x *ClearTierResponse) GetCleared() bool {
	if x != nil {
		return x.Cleared
	}
	return false
}

type ListTiersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTiersRequest) Reset() {
	*x = ListTiersRequest{}
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTiersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTiersRequest) ProtoMessage() {}

func (x *ListTiersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTiersRequest.ProtoReflect.Descriptor instead.
func (*ListTiersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_portcullis_v1_portcullis_proto_rawDescGZIP(), []int{13}
}

type TierInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity the entry applies to.
	Identity string `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// Tier name.
	Tier string `protobuf:"bytes,2,opt,name=tier,proto3" json:"tier,omitempty"`
	// Unix timestamp when the entry expires, or 0 when it never does.
	UntilUnix int64 `protobuf:"varint,3,opt,name=until_unix,json=untilUnix,proto3" json:"until_unix,omitempty"`
	// Where the entry came from.
	Source string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	// Audit record that produced the entry, when there was one.
	DecisionId    string `protobuf:"bytes,5,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TierInfo) Reset() {
	*x = TierInfo{}
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TierInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TierInfo) ProtoMessage() {}

func (x *TierInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TierInfo.ProtoReflect.Descriptor instead.
func (*TierInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_portcullis_v1_portcullis_proto_rawDescGZIP(), []int{14}
}

func (x *TierInfo) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *TierInfo) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *TierInfo) GetUntilUnix() int64 {
	if x != nil {
		return x.UntilUnix
	}
	return 0
}

func (x *TierInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TierInfo) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

type ListTiersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Active entries, ordered by identity.
	Tiers         []*TierInfo `protobuf:"bytes,1,rep,name=tiers,proto3" json:"tiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTiersResponse) Reset() {
	*x = ListTiersResponse{}
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTiersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTiersResponse) ProtoMessage() {}

func (x *ListTiersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTiersResponse.ProtoReflect.Descriptor instead.
func (*ListTiersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_portcullis_v1_portcullis_proto_rawDescGZIP(), []int{15}
}

func (x *ListTiersResponse) GetTiers() []*TierInfo {
	if x != nil {
		return x.Tiers
	}
	return nil
}

type ListDecisionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum records to return. Defaults to 100, capped at 1000.
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Only return records for this identity.
	Identity string `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	// Only return records with this judge label.
	Label         string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDecisionsRequest) Reset() {
	*x = ListDecisionsRequest{}
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDecisionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDecisionsRequest) ProtoMessage() {}

func (x *ListDecisionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDecisionsRequest.ProtoReflect.Descriptor instead.
func (*ListDecisionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_portcullis_v1_portcullis_proto_rawDescGZIP(), []int{16}
}

func (x *ListDecisionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDecisionsRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ListDecisionsRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type DecisionInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Audit record id.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Unix timestamp of the decision.
	AtUnix int64 `protobuf:"varint,2,opt,name=at_unix,json=atUnix,proto3" json:"at_unix,omitempty"`
	// Identity the decision was made for.
	Identity string `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	// Opaque suspect id used in the judge call.
	SuspectId string `protobuf:"bytes,4,opt,name=suspect_id,json=suspectId,proto3" json:"suspect_id,omitempty"`
	// Anomaly score.
	Score float64 `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	// Deterministic evidence flags.
	Evidence []string `protobuf:"bytes,6,rep,name=evidence,proto3" json:"evidence,omitempty"`
	// Judge that produced the verdict.
	Judge string `protobuf:"bytes,7,opt,name=judge,proto3" json:"judge,omitempty"`
	// Model version, when a model was involved.
	Model string `protobuf:"bytes,8,opt,name=model,proto3" json:"model,omitempty"`
	// Judge label.
	Label string `protobuf:"bytes,9,opt,name=label,proto3" json:"label,omitempty"`
	// Judge-reported confidence.
	Confidence float64 `protobuf:"fixed64,10,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Tier the policy proposed.
	ProposedTier string `protobuf:"bytes,11,opt,name=proposed_tier,json=proposedTier,proto3" json:"proposed_tier,omitempty"`
	// Tier the guardrails applied.
	AppliedTier string `protobuf:"bytes,12,opt,name=applied_tier,json=appliedTier,proto3" json:"applied_tier,omitempty"`
	// Tier in force before the decision.
	PreviousTier string `protobuf:"bytes,13,opt,name=previous_tier,json=previousTier,proto3" json:"previous_tier,omitempty"`
	// Guardrails that fired.
	GuardrailsApplied []string `protobuf:"bytes,14,rep,name=guardrails_applied,json=guardrailsApplied,proto3" json:"guardrails_applied,omitempty"`
	// Human-readable reason for the outcome.
	Reason string `protobuf:"bytes,15,opt,name=reason,proto3" json:"reason,omitempty"`
	// Judgment mode in force.
	Mode string `protobuf:"bytes,16,opt,name=mode,proto3" json:"mode,omitempty"`
	// Decision latency in milliseconds.
	LatencyMs float64 `protobuf:"fixed64,17,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// Bucketed, label-safe view of the suspect.
	Features      *FeatureInfo `protobuf:"bytes,18,opt,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionInfo) Reset() {
	*x = DecisionInfo{}
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionInfo) ProtoMessage() {}

func (x *DecisionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionInfo.ProtoReflect.Descriptor instead.
func (*DecisionInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_portcullis_v1_portcullis_proto_rawDescGZIP(), []int{17}
}

func (x *DecisionInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DecisionInfo) GetAtUnix() int64 {
	if x != nil {
		return x.AtUnix
	}
	return 0
}

func (x *DecisionInfo) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *DecisionInfo) GetSuspectId() string {
	if x != nil {
		return x.SuspectId
	}
	return ""
}

func (x *DecisionInfo) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *DecisionInfo) GetEvidence() []string {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *DecisionInfo) GetJudge() string {
	if x != nil {
		return x.Judge
	}
	return ""
}

func (x *DecisionInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DecisionInfo) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DecisionInfo) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DecisionInfo) GetProposedTier() string {
	if x != nil {
		return x.ProposedTier
	}
	return ""
}

func (x *DecisionInfo) GetAppliedTier() string {
	if x != nil {
		return x.AppliedTier
	}
	return ""
}

func (x *DecisionInfo) GetPreviousTier() string {
	if x != nil {
		return x.PreviousTier
	}
	return ""
}

func (x *DecisionInfo) GetGuardrailsApplied() []string {
	if x != nil {
		return x.GuardrailsApplied
	}
	return nil
}

func (x *DecisionInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DecisionInfo) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *DecisionInfo) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *DecisionInfo) GetFeatures() *FeatureInfo {
	if x != nil {
		return x.Features
	}
	return nil
}

// FeatureInfo is the bucketed view of a suspect that was sent to the judge.
type FeatureInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestRate      string                 `protobuf:"bytes,1,opt,name=request_rate,json=requestRate,proto3" json:"request_rate,omitempty"`
	DeniedShare      string                 `protobuf:"bytes,2,opt,name=denied_share,json=deniedShare,proto3" json:"denied_share,omitempty"`
	AuthFailShare    string                 `protobuf:"bytes,3,opt,name=auth_fail_share,json=authFailShare,proto3" json:"auth_fail_share,omitempty"`
	NotFoundShare    string                 `protobuf:"bytes,4,opt,name=not_found_share,json=notFoundShare,proto3" json:"not_found_share,omitempty"`
	ServerErrorShare string                 `protobuf:"bytes,5,opt,name=server_error_share,json=serverErrorShare,proto3" json:"server_error_share,omitempty"`
	TimingRegularity string                 `protobuf:"bytes,6,opt,name=timing_regularity,json=timingRegularity,proto3" json:"timing_regularity,omitempty"`
	RouteDiversity   string                 `protobuf:"bytes,7,opt,name=route_diversity,json=routeDiversity,proto3" json:"route_diversity,omitempty"`
	Methods          string                 `protobuf:"bytes,8,opt,name=methods,proto3" json:"methods,omitempty"`
	ClientFamily     string                 `protobuf:"bytes,9,opt,name=client_family,json=clientFamily,proto3" json:"client_family,omitempty"`
	SampledPaths     []string               `protobuf:"bytes,10,rep,name=sampled_paths,json=sampledPaths,proto3" json:"sampled_paths,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FeatureInfo) Reset() {
	*x = FeatureInfo{}
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureInfo) ProtoMessage() {}

func (x *FeatureInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureInfo.ProtoReflect.Descriptor instead.
func (*FeatureInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_portcullis_v1_portcullis_proto_rawDescGZIP(), []int{18}
}

func (x *FeatureInfo) GetRequestRate() string {
	if x != nil {
		return x.RequestRate
	}
	return ""
}

func (x *FeatureInfo) GetDeniedShare() string {
	if x != nil {
		return x.DeniedShare
	}
	return ""
}

func (x *FeatureInfo) GetAuthFailShare() string {
	if x != nil {
		return x.AuthFailShare
	}
	return ""
}

func (x *FeatureInfo) GetNotFoundShare() string {
	if x != nil {
		return x.NotFoundShare
	}
	return ""
}

func (x *FeatureInfo) GetServerErrorShare() string {
	if x != nil {
		return x.ServerErrorShare
	}
	return ""
}

func (x *FeatureInfo) GetTimingRegularity() string {
	if x != nil {
		return x.TimingRegularity
	}
	return ""
}

func (x *FeatureInfo) GetRouteDiversity() string {
	if x != nil {
		return x.RouteDiversity
	}
	return ""
}

func (x *FeatureInfo) GetMethods() string {
	if x != nil {
		return x.Methods
	}
	return ""
}

func (x *FeatureInfo) GetClientFamily() string {
	if x != nil {
		return x.ClientFamily
	}
	return ""
}

func (x *FeatureInfo) GetSampledPaths() []string {
	if x != nil {
		return x.SampledPaths
	}
	return nil
}

type ListDecisionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Audit records, newest first.
	Decisions     []*DecisionInfo `protobuf:"bytes,1,rep,name=decisions,proto3" json:"decisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDecisionsResponse) Reset() {
	*x = ListDecisionsResponse{}
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDecisionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDecisionsResponse) ProtoMessage() {}

func (x *ListDecisionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_portcullis_v1_portcullis_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDecisionsResponse.ProtoReflect.Descriptor instead.
func (*ListDecisionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_portcullis_v1_portcullis_proto_rawDescGZIP(), []int{19}
}

func (x *ListDecisionsResponse) GetDecisions() []*DecisionInfo {
	if x != nil {
		return x.Decisions
	}
	return nil
}

var File_api_proto_portcullis_v1_portcullis_proto protoreflect.FileDescriptor

const file_api_proto_portcullis_v1_portcullis_proto_rawDesc = "" +
	"\n" +
	"(api/proto/portcullis/v1/portcullis.proto\x12\rportcullis.v1\"W\n" +
	"\n" +
	"Attributes\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\"\x9d\x01\n" +
	"\fCheckRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06tokens\x18\x03 \x01(\x03R\x06tokens\x129\n" +
	"\n" +
	"attributes\x18\x04 \x01(\v2\x19.portcullis.v1.AttributesR\n" +
	"attributes\"\xb1\x01\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x1c\n" +
	"\tremaining\x18\x03 \x01(\x03R\tremaining\x12.\n" +
	"\x13retry_after_seconds\x18\x04 \x01(\x03R\x11retryAfterSeconds\x12\"\n" +
	"\rreset_at_unix\x18\x05 \x01(\x03R\vresetAtUnix\"K\n" +
	"\rStatusRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\"\x93\x01\n" +
	"\x0eStatusResponse\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x03R\tremaining\x12\"\n" +
	"\rreset_at_unix\x18\x03 \x01(\x03R\vresetAtUnix\x12)\n" +
	"\x10tokens_available\x18\x04 \x01(\x01R\x0ftokensAvailable\"J\n" +
	"\fResetRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\"C\n" +
	"\rResetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xae\x01\n" +
	"\rReportRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x06 \x01(\tR\tuserAgent\",\n" +
	"\x0eReportResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"y\n" +
	"\x0eSetTierRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x12\n" +
	"\x04tier\x18\x02 \x01(\tR\x04tier\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x99\x01\n" +
	"\x0fSetTierResponse\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x12\n" +
	"\x04tier\x18\x02 \x01(\tR\x04tier\x12\x1d\n" +
	"\n" +
	"until_unix\x18\x03 \x01(\x03R\tuntilUnix\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1f\n" +
	"\vdecision_id\x18\x05 \x01(\tR\n" +
	"decisionId\".\n" +
	"\x10ClearTierRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\"-\n" +
	"\x11ClearTierResponse\x12\x18\n" +
	"\acleared\x18\x01 \x01(\bR\acleared\"\x12\n" +
	"\x10ListTiersRequest\"\x92\x01\n" +
	"\bTierInfo\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x12\n" +
	"\x04tier\x18\x02 \x01(\tR\x04tier\x12\x1d\n" +
	"\n" +
	"until_unix\x18\x03 \x01(\x03R\tuntilUnix\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1f\n" +
	"\vdecision_id\x18\x05 \x01(\tR\n" +
	"decisionId\"B\n" +
	"\x11ListTiersResponse\x12-\n" +
	"\x05tiers\x18\x01 \x03(\v2\x17.portcullis.v1.TierInfoR\x05tiers\"^\n" +
	"\x14ListDecisionsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\"\xa5\x04\n" +
	"\fDecisionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aat_unix\x18\x02 \x01(\x03R\x06atUnix\x12\x1a\n" +
	"\bidentity\x18\x03 \x01(\tR\bidentity\x12\x1d\n" +
	"\n" +
	"suspect_id\x18\x04 \x01(\tR\tsuspectId\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\x12\x1a\n" +
	"\bevidence\x18\x06 \x03(\tR\bevidence\x12\x14\n" +
	"\x05judge\x18\a \x01(\tR\x05judge\x12\x14\n" +
	"\x05model\x18\b \x01(\tR\x05model\x12\x14\n" +
	"\x05label\x18\t \x01(\tR\x05label\x12\x1e\n" +
	"\n" +
	"confidence\x18\n" +
	" \x01(\x01R\n" +
	"confidence\x12#\n" +
	"\rproposed_tier\x18\v \x01(\tR\fproposedTier\x12!\n" +
	"\fapplied_tier\x18\f \x01(\tR\vappliedTier\x12#\n" +
	"\rprevious_tier\x18\r \x01(\tR\fpreviousTier\x12-\n" +
	"\x12guardrails_applied\x18\x0e \x03(\tR\x11guardrailsApplied\x12\x16\n" +
	"\x06reason\x18\x0f \x01(\tR\x06reason\x12\x12\n" +
	"\x04mode\x18\x10 \x01(\tR\x04mode\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x11 \x01(\x01R\tlatencyMs\x126\n" +
	"\bfeatures\x18\x12 \x01(\v2\x1a.portcullis.v1.FeatureInfoR\bfeatures\"\x8b\x03\n" +
	"\vFeatureInfo\x12!\n" +
	"\frequest_rate\x18\x01 \x01(\tR\vrequestRate\x12!\n" +
	"\fdenied_share\x18\x02 \x01(\tR\vdeniedShare\x12&\n" +
	"\x0fauth_fail_share\x18\x03 \x01(\tR\rauthFailShare\x12&\n" +
	"\x0fnot_found_share\x18\x04 \x01(\tR\rnotFoundShare\x12,\n" +
	"\x12server_error_share\x18\x05 \x01(\tR\x10serverErrorShare\x12+\n" +
	"\x11timing_regularity\x18\x06 \x01(\tR\x10timingRegularity\x12'\n" +
	"\x0froute_diversity\x18\a \x01(\tR\x0erouteDiversity\x12\x18\n" +
	"\amethods\x18\b \x01(\tR\amethods\x12#\n" +
	"\rclient_family\x18\t \x01(\tR\fclientFamily\x12#\n" +
	"\rsampled_paths\x18\n" +
	" \x03(\tR\fsampledPaths\"R\n" +
	"\x15ListDecisionsResponse\x129\n" +
	"\tdecisions\x18\x01 \x03(\v2\x1b.portcullis.v1.DecisionInfoR\tdecisions2\xc0\x02\n" +
	"\x12RateLimiterService\x12K\n" +
	"\x0eCheckRateLimit\x12\x1b.portcullis.v1.CheckRequest\x1a\x1c.portcullis.v1.CheckResponse\x12M\n" +
	"\x0eGetLimitStatus\x12\x1c.portcullis.v1.StatusRequest\x1a\x1d.portcullis.v1.StatusResponse\x12G\n" +
	"\n" +
	"ResetLimit\x12\x1b.portcullis.v1.ResetRequest\x1a\x1c.portcullis.v1.ResetResponse\x12E\n" +
	"\x06Report\x12\x1c.portcullis.v1.ReportRequest\x1a\x1d.portcullis.v1.ReportResponse2\xd4\x02\n" +
	"\fAdminService\x12H\n" +
	"\aSetTier\x12\x1d.portcullis.v1.SetTierRequest\x1a\x1e.portcullis.v1.SetTierResponse\x12N\n" +
	"\tClearTier\x12\x1f.portcullis.v1.ClearTierRequest\x1a .portcullis.v1.ClearTierResponse\x12N\n" +
	"\tListTiers\x12\x1f.portcullis.v1.ListTiersRequest\x1a .portcullis.v1.ListTiersResponse\x12Z\n" +
	"\rListDecisions\x12#.portcullis.v1.ListDecisionsRequest\x1a$.portcullis.v1.ListDecisionsResponseBGZEgithub.com/nshekhawat/portcullis/api/proto/portcullis/v1;portcullisv1b\x06proto3"

var (
	file_api_proto_portcullis_v1_portcullis_proto_rawDescOnce sync.Once
	file_api_proto_portcullis_v1_portcullis_proto_rawDescData []byte
)

func file_api_proto_portcullis_v1_portcullis_proto_rawDescGZIP() []byte {
	file_api_proto_portcullis_v1_portcullis_proto_rawDescOnce.Do(func() {
		file_api_proto_portcullis_v1_portcullis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_portcullis_v1_portcullis_proto_rawDesc), len(file_api_proto_portcullis_v1_portcullis_proto_rawDesc)))
	})
	return file_api_proto_portcullis_v1_portcullis_proto_rawDescData
}

var file_api_proto_portcullis_v1_portcullis_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_proto_portcullis_v1_portcullis_proto_goTypes = []any{
	(*Attributes)(nil),            // 0: portcullis.v1.Attributes
	(*CheckRequest)(nil),          // 1: portcullis.v1.CheckRequest
	(*CheckResponse)(nil),         // 2: portcullis.v1.CheckResponse
	(*StatusRequest)(nil),         // 3: portcullis.v1.StatusRequest
	(*StatusResponse)(nil),        // 4: portcullis.v1.StatusResponse
	(*ResetRequest)(nil),          // 5: portcullis.v1.ResetRequest
	(*ResetResponse)(nil),         // 6: portcullis.v1.ResetResponse
	(*ReportRequest)(nil),         // 7: portcullis.v1.ReportRequest
	(*ReportResponse)(nil),        // 8: portcullis.v1.ReportResponse
	(*SetTierRequest)(nil),        // 9: portcullis.v1.SetTierRequest
	(*SetTierResponse)(nil),       // 10: portcullis.v1.SetTierResponse
	(*ClearTierRequest)(nil),      // 11: portcullis.v1.ClearTierRequest
	(*ClearTierResponse)(nil),     // 12: portcullis.v1.ClearTierResponse
	(*ListTiersRequest)(nil),      // 13: portcullis.v1.ListTiersRequest
	(*TierInfo)(nil),              // 14: portcullis.v1.TierInfo
	(*ListTiersResponse)(nil),     // 15: portcullis.v1.ListTiersResponse
	(*ListDecisionsRequest)(nil),  // 16: portcullis.v1.ListDecisionsRequest
	(*DecisionInfo)(nil),          // 17: portcullis.v1.DecisionInfo
	(*FeatureInfo)(nil),           // 18: portcullis.v1.FeatureInfo
	(*ListDecisionsResponse)(nil), // 19: portcullis.v1.ListDecisionsResponse
}
var file_api_proto_portcullis_v1_portcullis_proto_depIdxs = []int32{
	0,  // 0: portcullis.v1.CheckRequest.attributes:type_name -> portcullis.v1.Attributes
	14, // 1: portcullis.v1.ListTiersResponse.tiers:type_name -> portcullis.v1.TierInfo
	18, // 2: portcullis.v1.DecisionInfo.features:type_name -> portcullis.v1.FeatureInfo
	17, // 3: portcullis.v1.ListDecisionsResponse.decisions:type_name -> portcullis.v1.DecisionInfo
	1,  // 4: portcullis.v1.RateLimiterService.CheckRateLimit:input_type -> portcullis.v1.CheckRequest
	3,  // 5: portcullis.v1.RateLimiterService.GetLimitStatus:input_type -> portcullis.v1.StatusRequest
	5,  // 6: portcullis.v1.RateLimiterService.ResetLimit:input_type -> portcullis.v1.ResetRequest
	7,  // 7: portcullis.v1.RateLimiterService.Report:input_type -> portcullis.v1.ReportRequest
	9,  // 8: portcullis.v1.AdminService.SetTier:input_type -> portcullis.v1.SetTierRequest
	11, // 9: portcullis.v1.AdminService.ClearTier:input_type -> portcullis.v1.ClearTierRequest
	13, // 10: portcullis.v1.AdminService.ListTiers:input_type -> portcullis.v1.ListTiersRequest
	16, // 11: portcullis.v1.AdminService.ListDecisions:input_type -> portcullis.v1.ListDecisionsRequest
	2,  // 12: portcullis.v1.RateLimiterService.CheckRateLimit:output_type -> portcullis.v1.CheckResponse
	4,  // 13: portcullis.v1.RateLimiterService.GetLimitStatus:output_type -> portcullis.v1.StatusResponse
	6,  // 14: portcullis.v1.RateLimiterService.ResetLimit:output_type -> portcullis.v1.ResetResponse
	8,  // 15: portcullis.v1.RateLimiterService.Report:output_type -> portcullis.v1.ReportResponse
	10, // 16: portcullis.v1.AdminService.SetTier:output_type -> portcullis.v1.SetTierResponse
	12, // 17: portcullis.v1.AdminService.ClearTier:output_type -> portcullis.v1.ClearTierResponse
	15, // 18: portcullis.v1.AdminService.ListTiers:output_type -> portcullis.v1.ListTiersResponse
	19, // 19: portcullis.v1.AdminService.ListDecisions:output_type -> portcullis.v1.ListDecisionsResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_portcullis_v1_portcullis_proto_init() }
func file_api_proto_portcullis_v1_portcullis_proto_init() {
	if File_api_proto_portcullis_v1_portcullis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_portcullis_v1_portcullis_proto_rawDesc), len(file_api_proto_portcullis_v1_portcullis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_portcullis_v1_portcullis_proto_goTypes,
		DependencyIndexes: file_api_proto_portcullis_v1_portcullis_proto_depIdxs,
		MessageInfos:      file_api_proto_portcullis_v1_portcullis_proto_msgTypes,
	}.Build()
	File_api_proto_portcullis_v1_portcullis_proto = out.File
	file_api_proto_portcullis_v1_portcullis_proto_goTypes = nil
	file_api_proto_portcullis_v1_portcullis_proto_depIdxs = nil
}
